---
- name: Install stuff from AppStore and brew
  hosts: localhost
  vars:
    mas_installed_apps:
      #Misc
      - { id: 1352778147, name: "Bitwarden" }
      #Office
      - { id: 462054704, name: "Microsoft Word" }
      - { id: 462058435, name: "Microsoft Excel" }
      - { id: 784801555, name: "Microsoft OneNote" }
      - { id: 462062816, name: "Microsoft PowerPoint" }
      #Foto-Apps
      - { id: 1541310539, name: "Luminar AI" }
    homebrew_installed_packages:
      - git
      - wget
      - maven
      - nmap
      - htop
      - node@14
    homebrew_taps:
      - AdoptOpenJDK/openjdk
    homebrew_cask_apps:
      - pycharm
      - intellij-idea
      - spotify
      - docker
      - github
      - adobe-creative-cloud
      - adoptopenjdk11
      - discord
      - teamviewer
  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas