---
- name: Install stuff from AppStore and brew
  hosts: localhost
  vars:
    mas_installed_apps:
      #Misc
      - { id: 1352778147, name: "Bitwarden" }
      #Office
      - { id: 462054704, name: "Microsoft Word" }
      - { id: 462058435, name: "Microsoft Excel" }
      - { id: 462062816, name: "Microsoft PowerPoint" }
    mas_upgrade_all_apps: true
    homebrew_upgrade_all_packages: true
    homebrew_upgrade_all_cask: true
    homebrew_installed_packages:
      - zsh
      - git
      - wget
      - maven
      - nmap
      - htop
      - hashicorp/tap/terraform
      - gradle
      - go
      - poetry
      - kompose
      - nvm
      - python
      - ansible
    homebrew_taps:
      - homebrew/cask-fonts
      - hashicorp/tap

    homebrew_cask_apps:
      - temurin@21
      - visual-studio-code
      - font-hack-nerd-font
      - font-fira-code-nerd-font
      - font-fira-mono-nerd-font
      - font-caskaydia-cove-nerd-font
      - font-meslo-for-powerline
      - font-meslo-lg-nerd-font
      - spotify
      - adobe-creative-cloud
      - nextcloud
      - ultimaker-cura
      - pycharm-ce
      - intellij-idea-ce
      - redisinsight
      - mqtt-explorer
      - arduino
      - cyberghost-vpn
      - pearcleaner
      - wifiman
      - tailscale
      - orbstack
      - obsidian
      - brave-browser
    homebrew_cask_uninstalled_apps:
      #- node@16

  tasks:
    - name: Return motd to registered var
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" && chsh -s $(which zsh) && source ~/.zshrc
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"

    - name: "zshrc-brew"
      lineinfile:
        path: ~/.zshrc
        line: "export PATH=/opt/homebrew/bin:$PATH"

    #- name: "zshrc-python3"
    #  lineinfile:
    #    path: ~/.zshrc
    #    line: "export PATH=/opt/homebrew/opt/python@3.11/libexec/bin:$PATH"
    - name: "zshrc-gopath"
      lineinfile:
        path: ~/.zshrc
        line: "export GOPATH=$HOME/go"
    - name: "zshrc-goinpath"
      lineinfile:
        path: ~/.zshrc
        line: "export PATH=$GOPATH/bin:$PATH"
    - name: Install Angular-CLI
      community.general.npm:
        name: "@angular/cli"
        global: yes
        state: present

    - name: Install http-server
      community.general.npm:
        name: "http-server"
        global: yes
        state: present

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
