---
- name: Install stuff from AppStore and brew
  hosts: localhost
  vars:
    mas_installed_apps:
      #Misc
      - { id: 1352778147, name: "Bitwarden" }
      - { id: 1274495053, name: "Microsoft To Do" }
      - { id: 1475387142, name: "Tailscale" }
      #Office
      - { id: 462054704, name: "Microsoft Word" }
      - { id: 462058435, name: "Microsoft Excel" }
      - { id: 784801555, name: "Microsoft OneNote" }
      - { id: 462062816, name: "Microsoft PowerPoint" }
      - { id: 497799835, name: "Xcode" }

    mas_upgrade_all_apps: true

    homebrew_upgrade_all_packages: true

    homebrew_installed_packages:
      - zsh
      - git
      - wget
      - maven
      - nmap
      - htop
      - node@14
      - python@3.9
      - terraform
      - gradle
      - go
      - poetry

    homebrew_taps:
      - AdoptOpenJDK/openjdk
      - homebrew/cask-fonts

    homebrew_cask_apps:
      - font-hack-nerd-font
      - font-fira-code-nerd-font
      - font-fira-mono-nerd-font
      - font-caskaydia-cove-nerd-font
      - font-meslo-lg-nerd-font
      - cyberduck
      - iterm2
      - spotify
      - github
      - adobe-creative-cloud
      - adoptopenjdk11
      - discord
      - teamviewer
      - google-chrome
      - nextcloud
      - robo-3t
      - ultimaker-cura
      - hyper
      - teamspeak-client
      - nvidia-geforce-now
      - pycharm-ce
      - intellij-idea-ce
      - league-of-legends
      - appcleaner
      - steam
    homebrew_cask_uninstalled_apps:
      - pycharm
      - intellij-idea

  tasks:
    - name: Return motd to registered var
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" && chsh -s $(which zsh) && source ~/.zshrc
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"

    - name: "zshrc-brew"
      lineinfile:
        path: ~/.zshrc
        line: "export PATH=/opt/homebrew/bin:$PATH"

    - name: "zshrc-python3"
      lineinfile:
        path: ~/.zshrc
        line: "export PATH=/opt/homebrew/opt/python@3.9/libexec/bin:$PATH"
    - name: "zshrc-gopath"
      lineinfile:
        path: ~/.zshrc
        line: "export GOPATH=$HOME/go"
    - name: "zshrc-goinpath"
      lineinfile:
        path: ~/.zshrc
        line: "export PATH=$GOPATH/bin:$PATH"
    - name: Install Angular-CLI
      community.general.npm:
        name: "@angular/cli"
        global: yes
        state: present

    - name: Install Vue-CLI
      community.general.npm:
        name: "@vue/cli"
        global: yes
        state: present

    - name: Install http-server
      community.general.npm:
        name: "http-server"
        global: yes
        state: present

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
